// components/Layout.js
import Head from 'next/head'
// import { Inter } from "next/font/google";
// import "@fontsource/inter"; // Default weight 400

import { Container, Row, Col } from 'react-bootstrap'

import Header from '@/components/header.js'
import Sidebar from '@/components/sidebar.js'
// import Footer from "@/components/footer";

import { ToastContainer } from 'react-toastify'

// const inter = Inter({ subsets: ["latin"] });

const Layout = ({ children }) => (
  <>
    <Head>
      <title>BPM ELF</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/bpm-elf/magician-hat.png" />
    </Head>
    <Header />
    <div className="my-flex">
      <Sidebar />
      <div
        as="main" // 與 <Main /> 無關
        className="content-container"
        // className={`${inter.className} content-container flex-grow-1`}
      >
        {children}
        <ToastContainer />
      </div>
    </div>
    {/* <Container fluid>
      <Row>
        <Col lg={2} className="p-0">
          <Sidebar />
        </Col>
        <Col lg={10} className="content-container">
          <div as="main" className={`${inter.className}`}>
            {children}
          </div>
        </Col>
      </Row>
    </Container> */}
    {/* <Footer /> */}
  </>
)

export default Layout
