// components/Layout.js
import Head from "next/head";
import { Inter } from "next/font/google";

import { Container, Row, Col } from "react-bootstrap";

import Header from "@/components/header";
import Sidebar from "@/components/sidebar";
// import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

const Layout = ({ children }) => (
  <>
    <Head>
      <title>BPM Guide</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/bpm-guide/favicon.ico" />
    </Head>
    <Header />
    <div className="d-flex">
      <Sidebar />
      <div
        as="main"
        className={`${inter.className} content-container flex-grow-1`}
      >
        {children}
      </div>
    </div>
    {/* <Container fluid>
      <Row>
        <Col lg={2} className="p-0">
          <Sidebar />
        </Col>
        <Col lg={10} className="content-container">
          <div as="main" className={`${inter.className}`}>
            {children}
          </div>
        </Col>
      </Row>
    </Container> */}
    {/* <Footer /> */}
  </>
);

export default Layout;
